version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install Pi-hole
          command: |
            apt-get update
            apt-get install -y wget
            wget -O /etc/pihole/setupVars.conf https://pastebin.com/raw/YBpWALGg
            curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash -s -- --unattended

workflows:
  version: 2
  your_workflow:
    jobs:
      - build
