version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install Pi-hole
          command: |
            cd "Pi-hole/automated install/"
            sudo bash basic-install.sh

workflows:
  version: 2
  your_workflow:
    jobs:
      - build

