version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Pi-hole
          command: |
            cd "pi-hole/automated install/"
            bash basic-install.sh

workflows:
  version: 2
  your_workflow:
    jobs:
      - build
